// <auto-generated />
using System;
using Ganache.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ganache.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191208224312_transactionMigrationV4")]
    partial class transactionMigrationV4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview4.19216.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ganache.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Credit_Amount");

                    b.Property<long>("Ether_Amount");

                    b.Property<string>("Recepient_publicKey");

                    b.Property<string>("Recepient_username");

                    b.Property<string>("Sender_publicKey");

                    b.Property<string>("Sender_username");

                    b.Property<DateTime>("TransactionDateTime");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Ganache.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Credit");

                    b.Property<string>("Email");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ganache.API.Models.Wallet", b =>
                {
                    b.Property<string>("Public_key");

                    b.Property<string>("Private_key");

                    b.Property<string>("UserId");

                    b.HasKey("Public_key");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
